name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build app
        run: bash ./scripts/buildprod.sh

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'notely-424913'
          install_components: 'docker'

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev

      - name: Submit build to Google Cloud Build
        run: gcloud builds submit --tag northamerica-northeast1-docker.pkg.dev/notely-424913/notely-ar-repo/notely .
