name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Goose
        uses: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build app
        run: bash ./scripts/buildprod.sh

      - name: Make migrate
        run: bash ./scripts/migrateup.sh

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Submit build to Google Cloud Build
        run: gcloud builds submit --tag northamerica-northeast1-docker.pkg.dev/notely-424913/notely-ar-repo/notely .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image northamerica-northeast1-docker.pkg.dev/notely-424913/notely-ar-repo/notely --region northamerica-northeast1 --allow-unauthenticated --project notely-424913 --max-instances=4

